modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="fanmakermod"
version="1.0.0"
displayName="FanMakerMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joris, MCreator"

[[dependencies.fanmakermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



